# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="/home/girol/.oh-my-zsh"

ZSH_THEME="spaceship"

# Spaceship customization
source ~/Projetos/dotfiles/zsh/spaceship-theme-customization

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
  git
  composer
  laravel5
)

source $ZSH/oh-my-zsh.sh

# Shell Tweaks
source ~/Projetos/dotfiles/shell_tweaks

# Personal Aliases
source ~/Projetos/dotfiles/aliases









